language: node_js
node_js:
    - "8.1.2"
branches:
    only:
        - master

before_script:
    - npm install -g firebase-tools

script:
    - firebase deploy --token $FIREBASE_TOKEN --bbw2020-fe79b --only-hosting
    - echo "Neue Runde neues Gl√ºck! Deploying!"
after_success:
    message: "jawollo!"

